apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoflask-deployment
  labels:
    app: demoflask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoflask
  template:
    metadata:
      labels:
        app: demoflask
    spec:
      containers:
      - name: demoflask
        image: yadhuprojects/demoflask:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_USER #MYSQL USER user_name from secret
          valueFrom:
            secretKeyRef:
              name: db-flask-credentials
              key: USER_NAME
        - name: MYSQL_PASSWORD #MYSQL PASSWORD password from secret
          valueFrom:
            secretKeyRef:
              name: db-flask-credentials
              key: PASSWORD
        - name: MYSQL_HOST # Setting Database Host from 'ConfigMap'
          valueFrom:
            configMapKeyRef:
              name: db-conf-flask
              key: host
        - name: MYSQL_DATABASE # Setting Database Name from 'ConfigMap'
          valueFrom:
            configMapKeyRef:
              name: db-conf-flask
              key: name
---
apiVersion: v1
kind: Service
metadata:
  name: demoflask-service
spec:
  type: NodePort
  selector:
    app: demoflask
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
---
apiVersion: v1
kind: Secret
metadata:
  name: db-flask-credentials
type: Opaque
data:
  USER_NAME: cm9vdA==
  PASSWORD: dG9vcjEyMw==
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf-flask
data:
 host: mysql
 name: TEST
